/** COIN TYPES */
export const SELECT_COIN = "SELECT_COIN";
export const FETCH_COINS_REQUEST = "FETCH_COINS_REQUEST";
export const FETCH_COINS_REQUEST_SUCCESS = "FETCH_COINS_REQUEST_SUCCESS";
export const FETCH_COINS_REQUEST_FAILURE = "FETCH_COINS_REQUEST_FAILURE";
export const FETCH_COIN_MARKET_CHART_REQUEST =
  "FETCH_COIN_MARKET_CHART_REQUEST";
export const SET_SEARCH_TERM_COINS = "SET_SEARCH_TERM_COINS";
export const RESET_COIN_MARKET_CHART = "RESET_COIN_MARKET_CHART";
export const RESET_COIN_DETAILED_DATA = "RESET_COIN_DETAILED_DATA";
export const RESET_COINS = "RESET_COINS";

export const FETCH_COIN_MARKET_CHART_REQUEST_SUCCESS =
  "FETCH_COIN_MARKET_CHART_REQUEST_SUCCESS";
export const FETCH_COIN_MARKET_CHART_REQUEST_FAILURE =
  "FETCH_COIN_MARKET_CHART_REQUEST_FAILURE";
export const FETCH_COIN_DETAILED_DATA = "FETCH_COIN_DETAILED_DATA";
export const FETCH_COIN_DETAILED_DATA_SUCCESS =
  "FETCH_COIN_DETAILED_DATA_SUCCESS";
export const FETCH_COIN_DETAILED_DATA_FAILURE =
  "FETCH_COIN_DETAILED_DATA_FAILURE";

/** PAGINATION */
export const SET_PAGINATION = "SET_PAGINATION";

/** FAVORITE COINS TYPES */
export const MARK_FAVORITE = "MARK_FAVORITE";
export const UNMARK_FAVORITE = "UNMARK_FAVORITE";
