export const FETCH_COINS_REQUEST = "FETCH_COINS_REQUEST";
export const FETCH_COINS_REQUEST_SUCCESS = "FETCH_COINS_REQUEST_SUCCESS";
export const FETCH_COINS_REQUEST_FAILURE = "FETCH_COINS_REQUEST_FAILURE";
